### ISSUE TITLE
Using CP.out

### ISSUE THREAD

**Issue by daniel-shimon** [anki-code/xonsh-operators-proposal#4]
In regards to [XEP2](https://github.com/anki-code/xonsh-operators-proposal/blob/main/XEP-2.rst):

1.  > Remove trailing new lines in CP.lines.

Maybe add that this will also affect iterating over a CP object? (`for line in $(...):`)

2. > Add str representation as "\n".join(CP.lines).

Do you mean `str($())`? Also, why not have it return `CP.out` instead of joining the lines?

3. > Add ``CP.str`` property to short access i.e. ``name = $(whoami).str``

This already exists as `CP.out`.
#### Note that `CP.output` is lazy and doesn't force the command to end, whereas `CP.out` waits for the command to wait so it is the real complete output and should generally be used instead of `CP.output`.

4. > *Optionally*. Add ``CP.o`` property as shortcut to access to ``output``.

Like I wrote, this exists as `CP.out`.

5. `echo -n @($(curl https://xon.sh).output) | wc -c` and `html = $(curl https://xon.sh).output` need to use `CP.out` instead.

**Comment by anki-code** [comment]
1. Added `__iter__` mention.

2-3-4. I agree. `str` removed.

5. Fixed.

Many thanks!
