### ISSUE TITLE
Update "Re-thinking the command substitution operators" issue

### ISSUE THREAD

**Issue by anki-code** [anki-code/xonsh-operators-proposal#5]
@daniel-shimon please update the [Re-thinking the command substitution operators](https://github.com/xonsh/xonsh/issues/3924) issue by [XEP-2](https://github.com/anki-code/xonsh-operators-proposal/blob/main/XEP-2.rst) proposals.

**Comment by daniel-shimon** [comment]
I've put a link in the proposal section, what would you like me to do?

**Comment by anki-code** [comment]
1. Rename header `https://github.com/anki-code/xonsh-operators-proposal (by @anki-code)` 
to `[XEP-2](https://github.com/anki-code/xonsh-operators-proposal/blob/main/XEP-2.rst)`

2. Remove:
```
Updated details in his proposal repo https://github.com/anki-code/xonsh-operators-proposal.

    $() returns an OutputLines object that unpacks as a list of lines from output, with added str functions.
    !() returns the complete output string in subproc mode - the same as $() before.
```
Because the details are in XEP-2 description.

3. Update the `Strip | Split | Xonsh` table along XEP-2 if it needed.

4. Remove:
```
OutputLines examples:

$(head /etc/passwd).lines_split(':')
#[['root', 'x', ... '/bin/bash'], ['daemon', 'x', ... '/usr/sbin/nologin']]

$(head -n 2 /etc/passwd).find('daemon')
# 32

$(head -n 2 /etc/passwd).lines_find('bin')
# [23, 26]  # positions of bin in every line
```

5. Update Pros/Cons sections along XEP-2.

**Comment by daniel-shimon** [comment]
Done 👍 
I've removed the pros/cons section because the XEP has changed a lot and these weren't really relevant anymore

**Comment by anki-code** [comment]
Haha, you removed all and it looks like adqm solution is what XEP-2 suggests:

<details>

![Screenshot_20201105_134141](https://user-images.githubusercontent.com/1708680/98230857-b2b3f800-1f6c-11eb-8e96-a7b3de6f81ed.png)

</details>

Please add the line "Read about XEP-2 proposal by the link" at least :)

Or enumerate the proposals: 1. XEP-2, 2. From adqm, 3. From laloch, etc :)

Thanks!

**Comment by daniel-shimon** [comment]
Sure haha

**Comment by anki-code** [comment]
Now looks great. Thanks!
