### ISSUE TITLE
How to get the complete output?

### ISSUE THREAD

**Issue by daniel-shimon** [anki-code/xonsh-operators-proposal#6]
I noticed there's no way in XEP-2 to get the output of a command without stripping because

> Remove trailing new lines in `CP.out`

How could a user get the complete output?

Maybe the stripping should only occur in `str(CP)`? this way `$()` in subproc is the same as `@($())` (which becomes `@(str($()))`), and the complete output can be retrieved via `$().out`, which won't break current usages.

**Comment by anki-code** [comment]
> How could a user get the complete output?

By using [`CP.raw_out`](https://github.com/xonsh/xonsh/pull/3925)

**Comment by daniel-shimon** [comment]
Hmm... OK I guess that's fine IMO

Maybe write about it in the XEP?

**Comment by anki-code** [comment]
Added to the questions section.
